ALTER TABLE BANKS
    ADD COLUMN PAYMENTS_URL VARCHAR(255);

CREATE TABLE PAYMENT_CONSENT
(
    BANKID             VARCHAR(64),
    CONSENTID          VARCHAR(255),
    CONSENT_RESPONSE   VARCHAR(16777216),
    DOMESTIC_PAYMENTID VARCHAR(255)
);
