/*
 * This Source Code Form is subject to the terms of the Mozilla
 * Public License, v. 2.0. If a copy of the MPL was not distributed
 * with this file, You can obtain one at
 *
 * https://mozilla.org/MPL/2.0/.
 */

/*
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.2
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.org.openbanking.v3_1_2.payments;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Meta Data relevant to the payload
 */
@ApiModel(description = "Meta Data relevant to the payload")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2019-07-09T18:27:25.589536+02:00[Europe/Budapest]")
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Meta {
    @JsonProperty("TotalPages")
    private Integer totalPages = null;

    @JsonProperty("FirstAvailableDateTime")
    private String firstAvailableDateTime = null;

    @JsonProperty("LastAvailableDateTime")
    private String lastAvailableDateTime = null;

    public Meta totalPages(Integer totalPages) {
        this.totalPages = totalPages;
        return this;
    }

    /**
     * Get totalPages
     *
     * @return totalPages
     **/
    @JsonProperty("TotalPages")
    @ApiModelProperty(value = "")
    public Integer getTotalPages() {
        return totalPages;
    }

    public void setTotalPages(Integer totalPages) {
        this.totalPages = totalPages;
    }

    public Meta firstAvailableDateTime(String firstAvailableDateTime) {
        this.firstAvailableDateTime = firstAvailableDateTime;
        return this;
    }

    /**
     * All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     *
     * @return firstAvailableDateTime
     **/
    @JsonProperty("FirstAvailableDateTime")
    @ApiModelProperty(value = "All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00")
    public String getFirstAvailableDateTime() {
        return firstAvailableDateTime;
    }

    public void setFirstAvailableDateTime(String firstAvailableDateTime) {
        this.firstAvailableDateTime = firstAvailableDateTime;
    }

    public Meta lastAvailableDateTime(String lastAvailableDateTime) {
        this.lastAvailableDateTime = lastAvailableDateTime;
        return this;
    }

    /**
     * All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00
     *
     * @return lastAvailableDateTime
     **/
    @JsonProperty("LastAvailableDateTime")
    @ApiModelProperty(value = "All dates in the JSON payloads are represented in ISO 8601 date-time format.  All date-time fields in responses must include the timezone. An example is below: 2017-04-05T10:43:07+00:00")
    public String getLastAvailableDateTime() {
        return lastAvailableDateTime;
    }

    public void setLastAvailableDateTime(String lastAvailableDateTime) {
        this.lastAvailableDateTime = lastAvailableDateTime;
    }

    @Override
    public int hashCode() {
        return Objects.hash(totalPages, firstAvailableDateTime, lastAvailableDateTime);
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Meta meta = (Meta) o;
        return Objects.equals(this.totalPages, meta.totalPages) &&
                Objects.equals(this.firstAvailableDateTime, meta.firstAvailableDateTime) &&
                Objects.equals(this.lastAvailableDateTime, meta.lastAvailableDateTime);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Meta {\n");

        sb.append("    totalPages: ").append(toIndentedString(totalPages)).append("\n");
        sb.append("    firstAvailableDateTime: ").append(toIndentedString(firstAvailableDateTime)).append("\n");
        sb.append("    lastAvailableDateTime: ").append(toIndentedString(lastAvailableDateTime)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

