/*
 * This Source Code Form is subject to the terms of the Mozilla
 * Public License, v. 2.0. If a copy of the MPL was not distributed
 * with this file, You can obtain one at
 *
 * https://mozilla.org/MPL/2.0/.
 */

/*
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.2
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.org.openbanking.v3_1_2.payments;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Identifies the nature of the postal address.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public enum OBAddressTypeCode {

    BUSINESS("Business"),

    CORRESPONDENCE("Correspondence"),

    DELIVERYTO("DeliveryTo"),

    MAILTO("MailTo"),

    POBOX("POBox"),

    POSTAL("Postal"),

    RESIDENTIAL("Residential"),

    STATEMENT("Statement");

    private final String value;

    OBAddressTypeCode(final String value) {
        this.value = value;
    }

    @JsonCreator
    public static OBAddressTypeCode fromValue(final String text) {
        for (final OBAddressTypeCode b : OBAddressTypeCode.values()) {
            if (String.valueOf(b.value).equals(text)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}

